from __future__ import annotations

from pathlib import Path
from typing import Final


DEFAULT_HOST: Final[str] = "localhost"
DEFAULT_PORT: Final[int] = 8765

DEFAULT_TOKEN_SEND_INTERVAL_S: Final[float] = 0.02
DEFAULT_DECODER_LEAD_MS: Final[int] = 2_000
DEFAULT_TIMING_MOCK_DECODER_LEAD_MS: Final[int] = 0
DEFAULT_TIMING_MOCK_ALIGN_DECODER_WINDOW: Final[bool] = False
DEFAULT_RESET_AFTER_AUDIO_END_MS: Final[int] = 2_000
DEFAULT_WALL_CLOCK_CHECK_INTERVAL_S: Final[float] = 0.05

DEFAULT_RUNTIME_DEVICE: Final[str] = "auto"
DEFAULT_BEATTHIS_DEVICE: Final[str] = "cpu"
DEFAULT_BEATTHIS_CHECKPOINT: Final[str] = "final0"
DEFAULT_BEATTHIS_FLOAT16: Final[bool] = False
DEFAULT_EAGER_LOAD_BEATTHIS: Final[bool] = True
TIMING_CANONICALIZATION_NONE: Final[str] = "none"
TIMING_CANONICALIZATION_BPM_80_160: Final[str] = "bpm-80-160"
TIMING_CANONICALIZATION_CHOICES: Final[tuple[str, ...]] = (
    TIMING_CANONICALIZATION_NONE,
    TIMING_CANONICALIZATION_BPM_80_160,
)
DEFAULT_DIFFICULTY: Final[float] = 4.0
SUPPORTED_DIFFICULTY_MIN: Final[float] = 2.0
SUPPORTED_DIFFICULTY_MAX: Final[float] = 6.0
DEFAULT_MAX_CONTROL_BATCH_SIZE: Final[int] = 12

DEFAULT_MAPPER_MODEL_ID: Final[str] = "mapper/default"
DEFAULT_TIMING_MOCK_MODEL_ID: Final[str] = "timing_mock/default"
MAPPER_V2_TUPLE_MODEL_ID: Final[str] = "mapper/v2_tuple"
MAPPER_V2_1_SPARSE_MODEL_ID: Final[str] = "mapper/v2_1_sparse"

DEFAULT_MAPPER_V2_CHECKPOINT_PATH: Final[Path] = Path(
    "artifacts/runs/stage2_mapper_v2/"
    "stage2_mapper_v2_phase_b_global_d768_l8_b1/checkpoint.pt",
)
DEFAULT_MAPPER_V2_1_CHECKPOINT_PATH: Final[Path] = Path(
    "artifacts/runs/stage2_mapper_v2_1/"
    "stage2_mapper_v2_1_phase_b_sparse_global_d384_l4_b2/checkpoint.pt",
)
DEFAULT_MAPPER_CHECKPOINT_PATH: Final[Path] = DEFAULT_MAPPER_V2_1_CHECKPOINT_PATH
DEFAULT_CONTROL_CHECKPOINT_PATH: Final[Path] = Path(
    "artifacts/runs/stage2_control_demo/"
    "stage2_control_demo_global_d384_l3_stride16_b6/checkpoints/checkpoint_step_002000.pt",
)

DEFAULT_MAPPER_PROFILE: Final[str] = "v2_1_sparse"
DEFAULT_MAPPER_CHECKPOINT_VERSION: Final[str] = "v2_1"
DEFAULT_MAPPER_MODEL_FAMILY: Final[str] = "mapper_v2_1"
DEFAULT_MAPPER_VOCAB_CONTRACT: Final[str] = "sparse_lane_actions"
DEFAULT_MAPPER_GRAMMAR_CONTRACT: Final[str] = "sparse_lane_action_grammar"
DEFAULT_MAPPER_DECODER_WINDOW_MS: Final[int] = 8_000
DEFAULT_MAPPER_MAX_TOKENS: Final[int] = 512
DEFAULT_MAPPER_TEMPERATURE: Final[float] = 0.0
DEFAULT_MAPPER_TOP_P: Final[float | None] = None
DEFAULT_USE_INCREMENTAL_MAPPER_DECODE: Final[bool] = True
DEFAULT_TIME_SHIFT_LENGTH_PENALTY: Final[float] = 5.2


__all__ = [
    "DEFAULT_BEATTHIS_CHECKPOINT",
    "DEFAULT_BEATTHIS_DEVICE",
    "DEFAULT_BEATTHIS_FLOAT16",
    "DEFAULT_CONTROL_CHECKPOINT_PATH",
    "DEFAULT_DECODER_LEAD_MS",
    "DEFAULT_DIFFICULTY",
    "DEFAULT_EAGER_LOAD_BEATTHIS",
    "DEFAULT_HOST",
    "DEFAULT_MAPPER_CHECKPOINT_PATH",
    "DEFAULT_MAPPER_CHECKPOINT_VERSION",
    "DEFAULT_MAPPER_DECODER_WINDOW_MS",
    "DEFAULT_MAPPER_GRAMMAR_CONTRACT",
    "DEFAULT_MAPPER_MAX_TOKENS",
    "DEFAULT_MAPPER_MODEL_FAMILY",
    "DEFAULT_MAPPER_MODEL_ID",
    "DEFAULT_MAPPER_PROFILE",
    "DEFAULT_MAPPER_TEMPERATURE",
    "DEFAULT_MAPPER_TOP_P",
    "DEFAULT_MAPPER_V2_1_CHECKPOINT_PATH",
    "DEFAULT_MAPPER_V2_CHECKPOINT_PATH",
    "DEFAULT_MAPPER_VOCAB_CONTRACT",
    "DEFAULT_MAX_CONTROL_BATCH_SIZE",
    "DEFAULT_PORT",
    "DEFAULT_RESET_AFTER_AUDIO_END_MS",
    "DEFAULT_RUNTIME_DEVICE",
    "DEFAULT_TIMING_MOCK_ALIGN_DECODER_WINDOW",
    "DEFAULT_TIMING_MOCK_DECODER_LEAD_MS",
    "DEFAULT_TIMING_MOCK_MODEL_ID",
    "DEFAULT_TIME_SHIFT_LENGTH_PENALTY",
    "DEFAULT_TOKEN_SEND_INTERVAL_S",
    "DEFAULT_USE_INCREMENTAL_MAPPER_DECODE",
    "DEFAULT_WALL_CLOCK_CHECK_INTERVAL_S",
    "MAPPER_V2_1_SPARSE_MODEL_ID",
    "MAPPER_V2_TUPLE_MODEL_ID",
    "SUPPORTED_DIFFICULTY_MAX",
    "SUPPORTED_DIFFICULTY_MIN",
    "TIMING_CANONICALIZATION_BPM_80_160",
    "TIMING_CANONICALIZATION_CHOICES",
    "TIMING_CANONICALIZATION_NONE",
]
