"""Scoped publication with timing-only lookahead and R1-owned complete rows."""
from dataclasses import asdict
import time

import numpy as np
import torch

from ..joint_audio_continuation.generation import NativeGeneration
from ..planned_audio_continuation.generation import HeadPlanner
from ..planned_audio_continuation.session import ContinuationSession, _BudgetStop
from ..planned_audio_continuation.spacing import row_release_window
from ..typed_audio_continuation.allocation import Allocation, LnFeedback, ln_episodes
from ..typed_audio_continuation.controls import ControlSchedule
from ..typed_audio_continuation.program import ACTIONS, Resources
from ..typed_audio_continuation.response_preference import RecoveryPreference


class ControlledSession(ContinuationSession):
    def __init__(self, model, mel, duration_ms, controls, *, seed=260926,
                 ln_feedback=LnFeedback(), recovery_preference=RecoveryPreference(head_pressure=4.),
                 max_seconds=120., head_times=None):
        controls = ControlSchedule(controls.spans, model.style_names)
        super().__init__(model, mel, duration_ms, seed=seed, planner_factory=HeadPlanner,
                         controls=controls, max_seconds=max_seconds, head_times=head_times)
        self.allocation = Allocation()
        self.ln_feedback, self.recovery_preference = ln_feedback, recovery_preference
        self.ln_scopes = ln_episodes(controls)
        self.recent_heads = ()

    @property
    def coverage(self):
        return self.cursor

    def row_options(self, now):
        span = next((s for s in self.ln_scopes if s.start_ms <= now < s.end_ms), None)
        self.allocation = self.allocation.in_scope(span)
        return dict(ln_shift=self.ln_feedback.log_odds_shift(self.allocation) if self.ln_feedback else 0.)

    def release_window(self, preview, profile):
        return row_release_window(self.replay, self.cursor, preview, self.duration_ms, profile)

    def prefer_rows(self, log_probs, legal, now):
        preference = self.recovery_preference
        if preference is None:
            return log_probs
        control = self.controls.at([now])
        stars = 2*control[0, 0]+4 if control[0, 2+len(self.model.style_names)] > 0 else np.nan
        cost = preference.row_cost(self.replay, now, stars)
        if now != self.duration_ms:
            ages = now-np.asarray(self.replay.open_ln_start_ms, float)
            cost += (ACTIONS == 3) @ preference.cost(ages, stars, 'hr')
        counts = np.isin(ACTIONS, (1, 2)).sum(-1)
        cost += preference.head_cost(Resources(starts=self.replay.open_ln_start_ms),
                                      self.recent_heads, now, counts, stars)
        return (log_probs-torch.as_tensor(cost, dtype=log_probs.dtype)).log_softmax(-1)

    def record_row(self, row):
        tap, ln = row.actions.count(1), row.actions.count(2)
        self.allocation = self.allocation.advance(tap, ln)
        if self.recovery_preference is not None:
            horizon = max(self.recovery_preference.hh_ms)
            self.recent_heads = tuple((t, h) for t, h in self.recent_heads if row.time_ms-t < horizon)
            if tap+ln:
                self.recent_heads += ((row.time_ms, tap+ln),)

    def publish_to(self, end_ms, *, minimum_rows=0):
        while self.cursor < self.duration_ms and (self.cursor < end_ms or len(self.rows) < minimum_rows):
            self.step(stop_at=self.duration_ms if len(self.rows) < minimum_rows else end_ms)
        return self.cursor

    def update_controls(self, span):
        if span.start_ms <= self.cursor:
            raise ValueError('A control update must start after published coverage')
        if not hasattr(self.planner, 'update_controls'):
            raise ValueError('A fixed diagnostic head plan cannot be regenerated by controls')
        controls = ControlSchedule((*self.controls.spans, span), self.model.style_names)
        recovery = self.model.recovery
        # R1 has already selected published rows against this short preview.
        # Preserve it through the response horizon; feeding TAP clocks back to
        # H sampling would violate the skeleton's information contract.
        retain = min(self.duration_ms, self.cursor+max(recovery.hh, recovery.hr+recovery.rh, 1+recovery.rh))
        self.planner.update_controls(controls, span.start_ms, self.cursor, retain_through_ms=retain)
        self.controls, self.ln_scopes = controls, ln_episodes(controls)
        self.residual = None


@torch.inference_mode()
def rollout(model, mel, duration_ms, controls, *, seed=260926, max_seconds=120.,
            on_window=None, head_times=None):
    started = time.perf_counter()
    session = ControlledSession(model, mel, duration_ms, controls, seed=seed,
                                max_seconds=max_seconds, head_times=head_times)
    windows = []
    reason = 'complete'
    try:
        while session.coverage < duration_ms:
            tick = time.perf_counter()
            session.publish_to(min(duration_ms, max(session.coverage, 0)+8000))
            windows.append(dict(coverage_ms=session.coverage, rows=len(session.rows),
                                service_seconds=time.perf_counter()-tick))
            if on_window is not None:
                on_window(session)
    except _BudgetStop as error:
        reason = str(error)
    completed = session.coverage == duration_ms and not any(session.replay.occupancy)
    return NativeGeneration(tuple(session.rows), completed, reason,
        session.coverage, dict(generation_seconds=time.perf_counter()-started,
            audio_seconds=session.audio_seconds, windows=windows,
            startup_seconds=windows[0]['service_seconds']+session.audio_seconds if windows else None,
            controls=[asdict(s) for s in session.controls.spans], recovery=asdict(model.recovery),
            sampling_contract='r1-release-window-v1',
            ln_feedback=asdict(session.ln_feedback), recovery_preference=asdict(session.recovery_preference),
            head_source='fixed-diagnostic' if head_times is not None else 'generated-audio',
            forced_deadline_releases=session.deadline_events))
