defaults:
  - planned_audio_inference_schema
  - _self_
  - override hydra/job_logging: disabled
  - override hydra/hydra_logging: disabled

hydra:
  run:
    dir: .
  job:
    chdir: false
  output_subdir: null
